/* Authored gallery. Add captions, community, date, role and story here; visitors can only view. */
window.GALLERY_CONFIG = [
  {
    "id": "photo-01",
    "number": "01",
    "original": "IMG_0327.HEIC",
    "src": "assets/gallery/photos/01-img_0327-thumb.webp",
    "fullSrc": "assets/gallery/photos/01-img_0327.webp",
    "caption": "Best Overall Award @ DI Cohort",
    "alt": "Five Threadit teammates holding certificates in front of colorful balloons.",
    "community": "Design Interactive Cohort",
    "date": "May 28, 2026",
    "role": "",
    "story": "I’m grateful for this team and the opportunity to learn, create, and grow together. Receiving Best Overall for Threadit made this moment especially meaningful—a shared celebration of the work we put in and the people who made it possible.",
    "angle": -5,
    "portrait": false,
    "width": 5712,
    "height": 4284,
    "shortCaption": "Best Overall Award"
  },
  {
    "id": "photo-02",
    "number": "02",
    "original": "IMG_0012.JPG",
    "src": "assets/gallery/photos/02-img_0012-thumb.webp",
    "fullSrc": "assets/gallery/photos/02-img_0012.webp",
    "caption": "#Include team · JCC presentation",
    "alt": "A group selfie at tables in a classroom.",
    "community": "#Include · Juvenile Caduceus Clinic (JCC) website project",
    "date": "June 2, 2026",
    "role": "",
    "story": "Our team after presenting the website project for Juvenile Caduceus Clinic (JCC). I’m grateful for the opportunity to work with such wonderful design teammates and a supportive lead, collaborate with the technical team, and create something for a real client. It was an honor to learn alongside this team and be part of the experience.",
    "angle": 3,
    "portrait": false,
    "width": 2048,
    "height": 1536,
    "shortCaption": "#Include team",
    "relatedPhotos": [
      {
        "id": "photo-04",
        "number": "04",
        "original": "IMG_2376.jpg",
        "src": "assets/gallery/photos/04-img_2376-thumb.webp",
        "fullSrc": "assets/gallery/photos/04-img_2376.webp",
        "caption": "More from the #Include team",
        "alt": "Eight friends posing in front of a classroom chalkboard.",
        "community": "#Include · Juvenile Caduceus Clinic (JCC) website project",
        "date": "June 2, 2026",
        "role": "",
        "story": "",
        "angle": 5,
        "portrait": false,
        "width": 1206,
        "height": 786
      }
    ]
  },
  {
    "id": "photo-03",
    "number": "03",
    "original": "IMG_0509.JPG",
    "src": "assets/gallery/photos/03-img_0509-thumb.webp",
    "fullSrc": "assets/gallery/photos/03-img_0509.webp",
    "caption": "DDF Spring 2026",
    "alt": "Design Fest participants sitting together with laptops in a classroom.",
    "community": "Design Interactive · Our first Design Fest",
    "date": "February 21, 2026",
    "role": "",
    "story": "Our first Design Fest, hosted by Design Interactive, was one of our most intense and challenging experiences. As a team, we learned so much about building a strong project and working together. I’m grateful for the experience, the lessons we carried forward, and the connections we made with mentors who continued to support us later in our journey.",
    "angle": -3,
    "portrait": false,
    "width": 3072,
    "height": 2304,
    "shortCaption": "DDF Spring 2026"
  },
  {
    "id": "photo-05",
    "number": "05",
    "original": "IMG_2377.jpg",
    "src": "assets/gallery/photos/05-img_2377-thumb.webp",
    "fullSrc": "assets/gallery/photos/05-img_2377.webp",
    "caption": "Dinner with Juliana",
    "alt": "Five friends sharing burgers at a restaurant.",
    "community": "Our mentor · Juliana",
    "date": "",
    "role": "",
    "story": "Dinner with our mentor, Juliana, whose guidance helped lead our team to victory. I’m grateful for her support, the lessons we learned from her, and the opportunity to share this moment together. Thank you, Juliana, for helping us along the way.",
    "angle": -2,
    "portrait": false,
    "width": 1206,
    "height": 769,
    "shortCaption": "Dinner with Juliana"
  },
  {
    "id": "photo-06",
    "number": "06",
    "original": "IMG_2378.jpg",
    "src": "assets/gallery/photos/06-img_2378-thumb.webp",
    "fullSrc": "assets/gallery/photos/06-img_2378.webp",
    "caption": "Japan study abroad · Skydea internship",
    "alt": "Two friends taking a mirror selfie.",
    "community": "UC Davis Design Summer Study Abroad · Skydea, Tokyo",
    "date": "June–August 2026",
    "role": "",
    "story": "I had the honor of traveling to Japan through the UC Davis Design Summer Study Abroad program and interning at Skydea, a UI/UX agency in Tokyo. The experience taught me so much about working at a company and introduced me to Japanese culture. I’m grateful for the opportunity to learn in a new environment and bring those experiences into my design journey.",
    "angle": 4,
    "portrait": false,
    "width": 1206,
    "height": 1085,
    "shortCaption": "A summer in Japan"
  },
  {
    "id": "photo-07",
    "number": "07",
    "original": "IMG_5204.JPEG",
    "src": "assets/gallery/photos/07-img_5204-thumb.webp",
    "fullSrc": "assets/gallery/photos/07-img_5204.webp",
    "caption": "Design community socials",
    "alt": "A large group gathered outdoors beneath flowering trees at night.",
    "community": "#Include · Design Interactive · Friends across backgrounds",
    "date": "",
    "role": "",
    "story": "Social nights with design friends from #Include, Design Interactive, and other clubs and backgrounds. I’m grateful for the connections that bring our wider design community together—a space to learn from one another, push each other to improve, and have fun along the way. These photos capture two different nights and the friendships that make the journey so meaningful.",
    "angle": -4,
    "portrait": false,
    "width": 4032,
    "height": 3024,
    "shortCaption": "Design friends",
    "relatedPhotos": [
      {
        "id": "photo-08",
        "number": "08",
        "original": "IMG_6050.jpg",
        "src": "assets/gallery/photos/08-img_6050-thumb.webp",
        "fullSrc": "assets/gallery/photos/08-img_6050.webp",
        "caption": "Another night with our design friends",
        "alt": "Friends posing outside beside a stone wall at night.",
        "community": "#Include · Design Interactive · Friends across backgrounds",
        "date": "",
        "role": "",
        "story": "",
        "angle": 2,
        "portrait": false,
        "width": 1206,
        "height": 789
      }
    ]
  },
  {
    "id": "photo-09",
    "number": "09",
    "original": "IMG_6396.JPG",
    "src": "assets/gallery/photos/09-img_6396-thumb.webp",
    "fullSrc": "assets/gallery/photos/09-img_6396.webp",
    "caption": "Design friends on the slopes",
    "alt": "Friends holding helmets in front of a lit snowy ski slope.",
    "community": "Friends from design clubs and different backgrounds",
    "date": "",
    "role": "",
    "story": "A trip to the slopes with friends we connected with through different design clubs and backgrounds. We brought everyone together to snowboard, ski, and spend time beyond our design work. I’m grateful for a community that keeps growing through shared experiences, new connections, and the fun we have together.",
    "angle": -5,
    "portrait": false,
    "width": 2304,
    "height": 1536,
    "shortCaption": "Together on the slopes"
  },
  {
    "id": "photo-10",
    "number": "10",
    "original": "IMG_7240.jpg",
    "src": "assets/gallery/photos/10-img_7240-thumb.webp",
    "fullSrc": "assets/gallery/photos/10-img_7240.webp",
    "caption": "Where our journey began",
    "alt": "Six friends posing together outdoors at night.",
    "community": "Design Interactive Fellowship · Our first friend group",
    "date": "",
    "role": "",
    "story": "As our design community grows, we never forget where we started. We met as beginners in UI/UX design through the Design Interactive Fellowship, forming our first friend group as we learned and started this journey together. Even as our circles expanded, we kept coming back together to reconnect and remember those beginnings. Some of us are transfer students, and we come from different majors, but a shared passion for design brought us together. I’m so grateful to have started alongside such talented, passionate, and fun people.",
    "angle": 3,
    "portrait": false,
    "width": 1206,
    "height": 885,
    "shortCaption": "Where we started",
    "relatedPhotos": [
      {
        "id": "photo-11",
        "number": "11",
        "original": "snapshoot 2.PNG",
        "src": "assets/gallery/photos/11-snapshoot-2-thumb.webp",
        "fullSrc": "assets/gallery/photos/11-snapshoot-2.webp",
        "caption": "Back together on the first day of school",
        "alt": "A decorated Snapshoot collage of four group photos.",
        "community": "Design Interactive Fellowship · Our first friend group",
        "date": "Fall 2026",
        "role": "",
        "story": "",
        "angle": -2,
        "portrait": true,
        "width": 686,
        "height": 1125
      }
    ]
  },
  {
    "id": "photo-12",
    "number": "12",
    "original": "IMG_3094.JPEG",
    "src": "assets/gallery/photos/12-img_3094-thumb.webp",
    "fullSrc": "assets/gallery/photos/12-img_3094.webp",
    "caption": "The day it all began",
    "alt": "A large community group posing in front of green and blue balloons.",
    "community": "Design Interactive Fellowship · UC Davis",
    "date": "Fall 2025",
    "role": "",
    "story": "My first quarter at UC Davis as a design transfer student, and the beginning of so many firsts. Design Interactive Fellowship was the first club I joined, the first community I became part of, where I made my first friends and friend group, and where I built my first project. This day holds so much meaning for me. I’m grateful for the people who welcomed me and gave me a place to learn, create, and grow. I wouldn’t be where I am today without this beginning.",
    "angle": 4,
    "portrait": false,
    "width": 6960,
    "height": 4640,
    "shortCaption": "My first community",
    "relatedPhotos": [
      {
        "id": "photo-13",
        "number": "13",
        "original": "what i do.JPG",
        "src": "assets/gallery/photos/13-what-i-do-thumb.webp",
        "fullSrc": "assets/gallery/photos/13-what-i-do.webp",
        "caption": "Our team presenting our first project",
        "alt": "Three people sharing a mobile prototype and research charts on laptops.",
        "community": "Design Interactive Fellowship · UC Davis",
        "date": "Fall 2025",
        "role": "",
        "story": "",
        "angle": -3,
        "portrait": false,
        "width": 1616,
        "height": 1080
      }
    ]
  }
];
